apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-deployment
  labels:
    app-label: fraud-detection-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app-label: fraud-detection-deployment
  template:
    metadata:
      labels:
        app-label: fraud-detection-deployment
    spec:
      containers:
      - name: fraud-detection-deployment
        image: image
        ports:
        - containerPort: 8000
        env:
        - name: DOCKERHUB_TOKEN
          value: "DOCKERHUB_TOKEN"
        - name: DOCKERHUB_USERNAME
          value: "DOCKERHUB_USERNAME"
        - name: MLFLOW_TRACKING_URI
          value: "MLFLOW_TRACKING_URI"
        - name: BOOTSTRAP_SERVERS
          value: "BOOTSTRAP_SERVERS"
        - name: KAFKA_PASSWORD
          value: "KAFKA_PASSWORD"
        - name: KAFKA_USERNAME
          value: "KAFKA_USERNAME"
