apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: fraud-detection
spec:
  endpoints:

  - path: /
    port: 8001
    scheme: http
    interval: 10s

  jobLabel: fraud-detection
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: fraud-detection