channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=24.2
- pip:
  - mlflow==2.16.0
  - jaraco-text==3.12.1
  - logging==0.4.9.6
  - numpy==2.1.0
  - pyspark==3.5.3
  - scipy==1.14.1
name: mlflow-env
